Feature: Test the guided interview
  In order to ensure that the guided interview behaves as expected, I
  want to test-drive it

  Scenario: Test the guided interview with two parents and one child
    Given I start the interview "docassemble.michildsupport:data/questions/childsupport.yml"
    Then I should see the phrase "What is the child support group?"
    And I click the "Two Parents" option
    And I click the button "Continue"
    Then I should see the phrase "How many children in the child support group?"
    And I select "1" as the "Number of children"
    And I click the button "Continue"
    Then I should see the phrase "What is the name of the first parent?"
    And I set "First name" to "John"
    And I set "Last name" to "Smith"
    And I click the button "Continue"
    Then I should see the phrase "What is the name of the second parent?"
    And I set "First name" to "Jane"
    And I set "Last name" to "Smith"
    And I click the button "Continue"
    Then I should see the phrase "What is the name and birthdate of the child?"
    And I set "First name" to "Thomas"
    And I set "Last name" to "Smith"
    And I set "Birth date" to "04/04/2006"
    And I click the button "Continue"
    Then I should see the phrase "What tax year do you want to use?"
    And I click the button "Continue"
    Then I should see the phrase "Do you have a court case?"
    And I click the button "Yes"
    Then I should see the phrase "Tell us about your court case."
    And I set "Case number" to "05-3432322"
    And I select "Huron" as the "County"
    And I click the button "Continue"
    Then I should see the phrase "Enter the number of overnights per year John Smith spends with Thomas Smith."
    And I set the first "Overnights per year" to "160"
    And I click the button "Continue"
    Then I should see the phrase "How many additional minor children does John Smith have from other relationships?"
    And I set "Number of additional minor children" to "1"
    And I click the button "Continue"
    Then I should see the phrase "Did John Smith and Jane Smith have any children together who are still minors and who are currently in the custody of someone other than John Smith or Jane Smith?"
    And I click the "Yes" option
    And I wait 1 second
    And I set "How many children?" to "1"
    And I click the button "Continue"
    Then I should see the phrase "Tell me about the income of John Smith."
    And I select "Employer Wages" as the first "Source"
    And I wait 3 seconds
    And I set "Employer name" to "ABC Inc."
    And I select "Monthly" as the "How often is the income received?"
    And I set "Gross income in this period" to "3200"
    And I set "Overtime in this period" to "0"
    And I set "Shift premium in this period" to "0"
    And I click the "Yes" option under "Is John Smith required to contribute a percentage of income to a retirement account?"
    And I wait 1 seconds
    And I set "What percentage of income is John Smith required to contribute?" to "5"
    And I click the button " Add another"
    And I wait 1 second
    And I select "Adoption Subsidy" as the second "Source"
    And I wait 3 seconds
    And I select "Monthly" as the second "How often is the income received?"
    And I set the second "Income in this period" to "32"
    And I click the button "Continue"
    Then I should see the phrase "Tell me about the tax exemptions of John Smith."
    And I set "Tax exemptions" to "2"
    And I select "Head of Household" as the "Filing status"
    And I select "Grand Rapids" as the "City of residence"
    And I select "Hamtramck" as the "City of employment"
    And I click the button "Continue"
    Then I should see the phrase "How do you want to determine the taxes of John Smith?"
    And I select "I know the tax amounts and will enter them" from the pull-down
    And I click the button "Continue"
    Then I should see the phrase "Tell me about the taxes of John Smith."
    And I select "Annually" as the "Taxation Frequency"
    And I set "Federal income tax" to "1000"
    And I set "State income tax" to "200"
    And I set "FICA tax" to "10"
    And I set "Resident local tax" to "0"
    And I set "Non-resident local tax" to "178"
    And I click the button "Continue"
    Then I should see the phrase "Does John Smith have any other deductions besides taxes?"
    And I click the button "Yes"
    Then I should see the phrase "Tell me about the non-tax deductions of John Smith."
    And I select "Required Union Dues" as the first "Source"
    And I set the first "Deduction amount" to "100"
    And I select "Monthly" as the first "Frequency"
    And I click the button " Add another"
    And I wait 1 second
    And I select "Spousal Support Paid to Another Party" as the second "Source"
    And I set the second "Deduction amount" to "10"
    And I select "Weekly" as the second "Frequency"
    And I click the button "Continue"
    Then I should see the phrase "Does John Smith have any childcare expenses?"
    And I click the button "Yes"
    Then I should see the phrase "Tell me about the childcare expenses of John Smith."
    And I click the "Actual" option under "Is this a potential or an actual expense?"
    And I set "Months in child care" to "10"
    And I set "Expense amount" to "100"
    And I select "Monthly" as the "Frequency"
    And I click the button "Continue"
    Then I should see the phrase "Do you know how much John Smith is entitled to from the Child and Dependent Care Tax Credit?"
    And I click the button "Yes"
    Then I should see the phrase "How much is John Smith entitled to under the Child and Dependent Care Tax Credit?"
    And I set "Amount" to "152"
    And I select "Monthly" as the "Frequency"
    And I click the button "Continue"
    Then I should see the phrase "How much does John Smith receive from child care subsidies and reimbursements?"
    And I set "Amount" to "75"
    And I select "Monthly" as the "Frequency"
    And I click the button "Continue"
    Then I should see the phrase "Is there a reason to change the date after which the child care costs of Thomas Smith will no longer be included in child support calculations?"
    And I click the button "Yes"
    Then I should see the phrase "What is the date after which the child care costs of Thomas Smith should no longer be included in child support calculations?"
    And I set "Date" to "5/5/2024"
    And I click the button "Continue"
    Then I should see the phrase "How much does John Smith pay for health care insurance?"
    And I set "Amount" to "56"
    And I select "Monthly" as the "Frequency"
    And I click the "No" option under "Is the health care insurance provided by a spouse or other household member?"
    And I click the "Yes" option under "Is Thomas Smith covered by this health insurance?"
    And I set "How many additional children are covered by this health insurance?" to "0"
    And I set "How many additional people are covered by this health insurance, including John Smith?" to "0"
    And I click the button "Continue"
    Then I should see the phrase "Does John Smith have any additional out-of-pocket medical expenses?"
    And I click the button "Yes"
    Then I should see the phrase "List the additional medical expenses of John Smith."
    And I set "Amount" to "566"
    And I select "Monthly" as the "Frequency"
    And I click the button "Continue"
    Then I should see the phrase "Is health care coverage accessible to the children and available at a reasonable cost for John Smith?"
    And I click the button "Yes"
    Then I should see the phrase "Is John Smith recommended to provide health care insurance?"
    And I click the button "Yes"
    Then I should see the phrase "Enter the number of overnights per year Jane Smith spends with Thomas Smith."
    And I set "Overnights per year" to "205"
    And I click the button "Continue"
    Then I should see the phrase "How many additional minor children does Jane Smith have from other relationships?"
    And I set "Number of additional minor children" to "1"
    And I click the button "Continue"
    Then I should see the phrase "Tell me about the income of Jane Smith."
    And I select "Employer Wages" as the first "Source"
    And I wait 3 seconds
    And I set "Employer name" to "DEF Inc."
    And I select "Monthly" as the "How often is the income received?"
    And I set "Gross income in this period" to "3000"
    And I set "Overtime in this period" to "100"
    And I set "Shift premium in this period" to "0"
    And I click the "No" option under "Is Jane Smith required to contribute a percentage of income to a retirement account?"
    And I click the button " Add another"
    And I wait 1 second
    And I select "Allowance for Rent" as the second "Source"
    And I wait 3 seconds
    And I select "Weekly" as the second "How often is the income received?"
    And I set the second "Income in this period" to "15"
    And I click the button "Continue"
    Then I should see the phrase "Tell me about the tax exemptions of Jane Smith."
    And I set "Tax exemptions" to "1"
    And I select "Single" as the "Filing status"
    And I select "Grayling" as the "City of residence"
    And I select "Lapeer" as the "City of employment"
    And I click the button "Continue"
    Then I should see the phrase "How do you want to determine the taxes of Jane Smith?"
    And I select "I don’t know the tax amounts; estimate monthly taxes for me" from the pull-down
    And I click the button "Continue"
    Then I should see the phrase "Does Jane Smith have any other deductions besides taxes?"
    And I click the button "Yes"
    Then I should see the phrase "Tell me about the non-tax deductions of Jane Smith."
    And I select "Life Insurance - Child Beneficiary" as the first "Source"
    And I set the first "Deduction amount" to "50"
    And I select "Monthly" as the first "Frequency"
    And I click the button "Continue"
    Then I should see the phrase "Does Jane Smith have any childcare expenses?"
    And I click the button "Yes"
    Then I should see the phrase "Tell me about the childcare expenses of Jane Smith."
    And I click the "Potential" option under "Is this a potential or an actual expense?"
    And I set "Months in child care" to "2"
    And I set "Expense amount" to "230"
    And I select "Monthly" as the "Frequency"
    And I click the button "Continue"
    Then I should see the phrase "Do you know how much Jane Smith is entitled to from the Child and Dependent Care Tax Credit?"
    And I click the button "Yes"
    Then I should see the phrase "How much is Jane Smith entitled to under the Child and Dependent Care Tax Credit?"
    And I set "Amount" to "51"
    And I select "Monthly" as the "Frequency"
    And I click the button "Continue"
    Then I should see the phrase "How much does Jane Smith receive from child care subsidies and reimbursements?"
    And I set "Amount" to "98"
    And I select "Monthly" as the "Frequency"
    And I click the button "Continue"
    Then I should see the phrase "How much does Jane Smith pay for health care insurance?"
    And I set "Amount" to "51"
    And I select "Monthly" as the "Frequency"
    And I click the "No" option under "Is the health care insurance provided by a spouse or other household member?"
    And I click the "Yes" option under "Is Thomas Smith covered by this health insurance?"
    And I set "How many additional children are covered by this health insurance?" to "0"
    And I set "How many additional people are covered by this health insurance, including Jane Smith?" to "0"
    And I click the button "Continue"
    Then I should see the phrase "Does Jane Smith have any additional out-of-pocket medical expenses?"
    And I click the button "No"
    Then I should see the phrase "Is health care coverage accessible to the children and available at a reasonable cost for Jane Smith?"
    And I click the button "Yes"
    Then I should see the phrase "Is Jane Smith recommended to provide health care insurance?"
    And I click the button "Yes"
    And I wait forever
